# https://www.freecodecamp.org/news/publishing-github-event-data-with-github-actions-and-pages/
# https://stackoverflow.com/questions/58597010/how-to-access-a-github-issue-comment-body-using-github-actions
# This is a basic workflow to help you get started with Actions
# https://github.com/maguowei/iaas/blob/d48834c18b66ae0f3ae32e5e62a6811dfddadcb2/.github/workflows/iaas.yml
# replace invalid characters in filename https://stackoverflow.com/a/50876753/1553656

name: issue2post
description: "Turn issues into markdown file"
branding:
  icon: "archive"
  color: "green"
inputs:
  branch:
    description: "Target branch name to push the markdownfile"
    required: true
    default: "master"
  dir:
    description: "the posts dir"
    required: true
    default: "_posts"
  GITHUB_TOKEN:
    description: "secrets.GITHUB_TOKEN"
    required: true
  created_at:
    description: "github.event.issue.created_at"
    required: true
  updated_at:
    description: "github.event.issue.updated_at"
    required: true
  label_name:
    description: "github.event.issue.label[name]"
    required: true
  title:
    description: "github.event.issue.title"
    required: true
  body:
    description: "github.event.issue.body"
    required: true
  number:
    description: "github.event.issue.bumber"
    required: true
  actor:
    description: "github.actor"
    required: true
  nohead:
    description: "no create/update/..."
    required: true
runs:
  using: "composite"
  steps:
    - id: generate-markdown-file
      name: Turn comment into file
      shell: bash
      run: |
        mkdir -p ${{ inputs.dir }}
        ISSUE4NUMBER=$(printf '%04d' ${{ inputs.number }})
        if ls ${{ inputs.dir }}/${ISSUE4NUMBER}_*.md &> /dev/null;then
          ls ${{ inputs.dir }}/${ISSUE4NUMBER}_* |xargs -i rm {}
        fi
        POST_TITLE=${ISSUE4NUMBER}_$(sed -E 's/[[:space:]|[:punct:]]/_/g' <<< '${{ inputs.title }}')
        cat <<'EOF' >  "${{ inputs.dir }}/${POST_TITLE}".md
        ${{ inputs.body }}
        EOF
        IN_TITLE=$(cat "${{ inputs.dir }}/${POST_TITLE}".md |grep "# "|awk '{print $2}'|tr -d '\n')
        echo ${IN_TITLE}
        ROOTTITLE="# [${IN_TITLE}](https://github.com/${{ github.repository }}/issues/${{ inputs.number }})"
        echo ${ROOTTITLE}
        sed -i '1i\'"${ROOTTITLE}"'' "${{ inputs.dir }}/${POST_TITLE}".md
    - name: Push changes to repo
      shell: bash
      run: |
        REMOTE=https://${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git config user.email "${{ inputs.actor }}@users.noreply.github.com"
        git config user.name "${{ inputs.actor }}"
        git pull ${REMOTE}
        git checkout ${{ inputs.branch }}
        git add "${{ inputs.dir }}"
        git status
        git commit -am "Add new comment"
        git push ${REMOTE} ${{ inputs.branch }}
